// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"thsr/m/internal/injector/api"
	"thsr/m/server/receiver"
	"thsr/m/server/receiver/webhook"
	"thsr/m/service/lineBot"
)

// Injectors from wire.go:

func BuildInjector() *Injector {
	service := lineBot.New()
	webhookReceiver := webhook.ProvideReceiver(service)
	v := api.ProvideReceiverList(webhookReceiver)
	ginRouter := receiver.ProvideRoute(v...)
	injector := &Injector{
		Receiver: ginRouter,
	}
	return injector
}
